### ISSUE TITLE
Job submit grid find error

### ISSUE THREAD

**Issue by vankesteren** [roctoproject/rocto-client#5]
Job submit looks for literal folder named "roctoJob" but should just recurse into first folder in the `.rocto` file. This folder name changes based on the name chosen by the user in the `R` package

**Comment by oguzhanogreden** [comment]
A good one for me to get reacquainted :)

**Comment by oguzhanogreden** [comment]
https://github.com/roctoproject/rocto-client/blob/master/rocto_client/client/client.py#L78

This is what you're talking about right?

**Comment by vankesteren** [comment]
yes!
