### ISSUE TITLE
submit_task() doesn't send meta

### ISSUE THREAD

**Issue by oguzhanogreden** [roctoproject/rocto-client#9]
submit_task() does not send `meta`, see [here](https://github.com/roctoproject/rocto-docs/issues/1) for API specification.

**Comment by oguzhanogreden** [comment]
@vankesteren can you let me know when the server is up to API v0.2.0 so we can test this?

**Comment by vankesteren** [comment]
Now! With [this part](https://github.com/roctoproject/rocto-server/commit/e4636fb4970c3db53e3f67ab40059aadc47a0005#diff-1ff76b41088a016a3f2fd7dbb9f4c163L43). Note that I updated ALL communication to api version 0.2.0. Also the `R` package is up-to-date.
